settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.toronton.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: ratrating.com
    name: ratrating.com
    description: 'ratrating.com'
    url: 'https://ratrating.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: nodehh
    name: nodehh
    url: 'https://nodeh.555000777.xyz/'
    method: GET
    expectStatus: 200
    
  - id: renthibiny.ru
    name: renthibiny.ru
    url: 'https://renthibiny.ru/'
    method: GET
    expectStatus: 200

  - id: netru.555000777.xyz
    name: netru.555000777.xyz
    url: 'https://netru.555000777.xyz/'
    method: GET
    expectStatus: 200
