name = "cf-workers-status-page"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["*/2 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="246ae8c2f7704bd386cc29421a546917", preview_id=""}]
#zone_id="xxx"
#route="xxx"
